# Generated by Django 3.2.7 on 2021-09-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Оценка'},
        ),
    ]
